### PR TITLE
Moved Docker configurations from subscription-use-cases#59 for CI

### PR DESCRIPTION
**Pull request by hibariya**
Hello! I've moved Docker configuration files from the PR and arranged them to make sure that they can run on GitHub Actions. I believe now we can discuss how we can test sample repositories on CI. I'd appreciate your advice.

Let me explain the current status, some changes, and issues.

I've confirmed that we can run tests for every sample on GitHub Actions. [Here's the latest job](https://github.com/stripe-samples/sample-ci/runs/1211924227?check_suite_focus=true). The job runs tests for each server-side sample on subscription-use-cases. For now, the tests just request to root path. I've pushed dummy RSpec tests into [ci branch on subscription-use-cases](https://github.com/stripe-samples/subscription-use-cases/compare/master...hibariya:ci). 

Since we cannot mount local-directory on GitHub Actions, I added Dockerfiles for each language to copy application code to container images. I also added [spike.sh](https://github.com/stripe-samples/sample-ci/compare/master...ci#diff-f3a53fd6b7980050ddcc8515e62c65d7) as a demo to run tests for subscription-use-cases. We can run it either on GitHub Actions or the local machine.

There is an issue. I've faced an error while running [per_seat_server_spec.rb](https://github.com/stripe-samples/subscription-use-cases/blob/master/spec/per_seat_server_spec.rb#L27) with the Python implementation as follows. So far, I have no idea why this happens. It can be reproduced by running [fail_per_seat_python.sh](https://github.com/stripe-samples/sample-ci/compare/master...ci#diff-2e4b766e0f4b7af46e83db5d72d62dc2) locally. 

```
Failures:

  1) full integration path just works
     Failure/Error: expect(subscription["id"]).to start_with("sub_")
       expected nil to start with "sub_", but it cannot be indexed using #[]
     # ./spec/per_seat_server_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 1.76 seconds (files took 0.29676 seconds to load)
1 example, 1 failure
```

The content of the `subscription` here was:

```ruby
{"error"=>{"message"=>"Request req_u4BBWiCkQe7d7Q: The customer does not have a payment method with the ID pm_1HZ2AdCWW2eVYDoPZcCgtZrM. The payment method must be attached to the customer."}}
```

### CODE REVIEW

**Comment by cjavilla-stripe** [comment]
WOW! This is awesome, @hibariya! Going to read through now.

**Comment by hibariya** [comment]
Thank you :)

I forgot to mention the environment variables which `spike.sh` and  `fail_per_seat_python.sh` need. The following variables will be needed.

```bash
export STRIPE_PUBLISHABLE_KEY=(the key)
export STRIPE_SECRET_KEY=(the key)
export STRIPE_WEBHOOK_SECRET=whsec_1234
export BASIC=price_1HXyXwCWW2eVYDoPnnTQ02VO
export PREMIUM=price_1HXyVBCWW2eVYDoPtXcEdXfw
```

**Comment by cjavilla-stripe** [comment]
Okay. I recently upgraded docker-compose. I'm not sure if that's the cause, but getting this error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/main.py", line 67, in main
    command()
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/main.py", line 123, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/command.py", line 131, in get_project
    client = get_client(
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(**kwargs)
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/docker/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/Cellar/docker-compose/1.27.4/libexec/lib/python3.8/site-packages/docker/api/client.py", line 212, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

```

**Comment by cjavilla-stripe** [comment]
What should these env variables be? 

WARNING: The SERVER_LANG variable is not set. Defaulting to a blank string.
WARNING: The SAMPLE variable is not set. Defaulting to a blank string.
WARNING: The STATIC_DIR variable is not set. Defaulting to a blank string.

**Comment by hibariya** [comment]
Hmm, I have never seen this message. Do either restarting Docker or rebooting the machine help?

My Docker and docker-compose are the following versions:

```
$ docker-compose version
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.7.8
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

$ docker version
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.14.7
 Git commit:        4484c46d9d
 Built:             Sat Oct  3 12:34:13 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.7
  Git commit:       4484c46d9d
  Built:            Sat Oct  3 12:33:31 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

**Comment by cjavilla-stripe** [comment]
I'll try restarting my machine next :) 


❯ docker-compose version
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

❯ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.14
 Git commit:        afacb8b
 Built:             Thu Mar 12 02:45:08 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by hibariya** [comment]
> WARNING: The SERVER_LANG variable is not set. Defaulting to a blank string.
> WARNING: The SAMPLE variable is not set. Defaulting to a blank string.
> WARNING: The STATIC_DIR variable is not set. Defaulting to a blank string.

These are OK. They show up because when the script builds the runner container, these environment variables are not present yet. Sorry for the mess :pray:

**Comment by hibariya** [comment]
Hello. I've modified the settings and shell scripts to generate `docker-compose.yml` and `docker-compose.override.yml` instead of setting `COMPOSE_FILES` (115ddd9). Additionally, most non-secret variables in these files will be substituted in advance.

* `docker-compose.yml`: this will be generated from `docker/docker-compose.base.yml`
* `docker-compose.override.yml`: this will be generated from `docker/${SERVER_LANG}/docker-compose.web.yml`

I think it will make debugging on local machines easier. 

```bash
$ ./fail_per_seat_python.sh # when one of the tests fails

$ cd subscription-use-cases/
$ docker-compose logs # we can inspect containers like this without setting additional environment variables
                      # other than the variables that mentioned in the earlier comment
```

**Comment by hibariya** [comment]
@cjavilla-stripe Hi. Could you set up the customer portal for the test account? While I was trying to run tests for stripe-samples/checkout-single-subscription, I got an error like this:

> web_1     | com.stripe.exception.InvalidRequestException: You can’t create a portal session in test mode until you save your customer portal settings in test mode at https://dashboard.stripe.com/test/settings/billing/portal.; request-id: req_0UWeFwL9fAUqMF

Logs: https://github.com/stripe-samples/sample-ci/runs/1317960027?check_suite_focus=true#step:6:194

The price ids these tests use are https://github.com/stripe-samples/sample-ci/actions/runs/332512201/workflow#L60-L61

**Comment by cjavilla-stripe** [comment]
Updated. The account should now support these requests. Re running the job now.

**Comment by hibariya** [comment]
Thanks! It worked.

I've been trying to create YAML files for the following repositories' CI. 

* [stripe-samples/checkout-one-time-payments](https://github.com/stripe-samples/sample-ci/pull/1/files#diff-b416528a6675e0565bde8ddb94af0f19cfe98e5f9ce4222e17fffea748857546)
* [stripe-samples/checkout-single-subscription](https://github.com/stripe-samples/sample-ci/pull/1/files#diff-751f114b6b807caacecc2e730124e2175a6718abbeb9cd39d86635d54b59c5d9)
* [stripe-samples/subscription-use-cases](https://github.com/stripe-samples/sample-ci/pull/1/files#diff-83de099cfd93f63141ef4fbeacca07207e7f95024a0ef6e24df088fe6a18469c)

Now, each YAML file should work well with a little tweak on the checkout steps on the corresponding repository. I'm planning to move these YAML files to the repositories when we confirmed we could start CI this way.

To make sure it works well, I'll try applying similar settings for several other repositories, too. If you find any concerns/problems at the moment, feel free to point it out to me. Anyway, I'd like to share the details with you at the next meeting.

**Comment by cjavilla-stripe** [comment]
Okay yeah let's chat at the next meeting. :) Excited these are passing!

**Comment by hibariya** [comment]
Hi. I've added node-typescript support and moved each workflow file to its corresponding repository. After merging this PR, the following could be merged.

* https://github.com/stripe-samples/subscription-use-cases/pull/65
* https://github.com/stripe-samples/checkout-single-subscription/pull/38
* https://github.com/stripe-samples/checkout-one-time-payments/pull/49
* https://github.com/stripe-samples/accept-a-card-payment/pull/52

**Comment by cjavilla-stripe** [comment]
Awesome lets do it! Feel free to merge this one when you're ready and I'll review the others.

**Review by cjavilla-stripe — APPROVED** [review]
LGTM

**Pull request merged**
